In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [4]:
df

,cgpa,profile_score,lpa
0,8,8,4
1,7,9,5
2,6,10,6
3,5,12,7


In [5]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):

        parameters['W' + str(l)] = np.ones((layer_dims[l-1], layer_dims[l]))*0.1
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))

    return parameters
        

In [6]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'b2': array([[0.]])}

In [7]:
 def linear_forward(A_prev,W,b):
     Z = np.dot(W.T,A_prev) + b
     return Z

In [8]:
#Forward Propagation 
def L_layer_forward(X,parameters):
    A=X
    L=len(parameters)//2 # numbers of layers in the neural networks

    for l in range(1,L+1):
        A_prev = A
        W1 = parameters['W' + str(l)]
        b1 = parameters['b' + str(l)]
        # print("A"+str(l-1)+": ",A_prev)
        # print("W" +str(l)+": ",W1)
        # print("b"+str(l)+": ",b1)
        # print("--"*20)

        A = linear_forward(A_prev, W1, b1)
        # print("A"+str(l)+": ",A)
        # print("**"*20)
    return A,A_prev

In [9]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
y = df[['lpa']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X, parameters)

In [10]:
(y-0.32)**2

np.float64(13.5424)

In [11]:
y_hat = y_hat[0][0]

In [12]:
A1

array([[1.6],
       [1.6]])

In [13]:
def update_parameters(parameters,y,y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001*2*(y-y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001*2*(y-y_hat)*A1[1][0])
    parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001*2*(y-y_hat))

    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001*2*(y-y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['b1'][0][0] = parameters['b1'][0][0] + (0.001*2*(y-y_hat)*parameters['W2'][0][0])

    parameters['W1'][1][0] = parameters['W1'][1][0] + (0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001*2*(y-y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['b1'][1][0] = parameters['b1'][1][0] + (0.001*2*(y-y_hat)*parameters['W2'][1][0])

In [14]:
update_parameters(parameters,y,y_hat,A1,X)

In [15]:
parameters


{'W1': array([[0.10658137, 0.10658137],
        [0.10658137, 0.10658137]]),
 'b1': array([[0.00082267],
        [0.00082267]]),
 'W2': array([[0.111776],
        [0.111776]]),
 'b2': array([[0.119136]])}

In [16]:
X = df[['cgpa','profile_score']].values[1].reshape(2,1)
y = df[['lpa']].values[1][0]



y_hat,A1 = L_layer_forward(X, parameters)

In [17]:
update_parameters(parameters,y,y_hat,A1,X)

/tmp/ipykernel_16/3580889262.py:2: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001*2*(y-y_hat)*A1[0][0])
/tmp/ipykernel_16/3580889262.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001*2*(y-y_hat)*A1[1][0])
/tmp/ipykernel_16/3580889262.py:4: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.001*2*(y-y_hat)

In [18]:
# epochs impementation
parameters = initialize_parameters([2,2,1])
epochs=5

for i in range(epochs):
    Loss=[]
    for j in range(df.shape[0]):
        X = df[['cgpa','profile_score']].values[j].reshape(2,1) #Shape(no of features, no. of training example)
        y = df[['lpa']].values[j][0] 
        
        # Parameter initialization

        y_hat,A1 = L_layer_forward(X,parameters)
        y_hat = y_hat[0][0]

        update_parameters(parameters,y,y_hat,A1,X)
        Loss.append((y-y_hat)**2)
    print('Epochs - ',i+1,"Loss - ",np.array(Loss).mean())
parameters

Epochs -  1 Loss -  25.321744156025517
Epochs -  2 Loss -  18.320004165722047
Epochs -  3 Loss -  9.473661050729628
Epochs -  4 Loss -  3.2520938634031613
Epochs -  5 Loss -  1.3407132589299962


{'W1': array([[0.26507636, 0.38558861],
        [0.27800387, 0.40980287]]),
 'b1': array([[0.02749056],
        [0.02974394]]),
 'W2': array([[0.41165744],
        [0.48302736]]),
 'b2': array([[0.48646246]])}

In [19]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Input


In [20]:
model = Sequential()
model.add(Input(shape=(2,)))
model.add(Dense(2,activation='linear'))
model.add(Dense(1,activation='linear'))

2026-08-20 20:16:18.079319: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


In [21]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
model.get_weights()

[array([[-1.2028754,  0.9025043],
        [ 0.1957984, -0.5931602]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.51865673],
        [-1.3311985 ]], dtype=float32),
 array([0.], dtype=float32)]

In [23]:
new_weights = [np.array([[0.1,0.1],
                        [0.1,0.1]], dtype=np.float32),
              np.array([0.,0.], dtype=np.float32),
              np.array([[0.1],
                       [0.1]], dtype=np.float32),
              np.array([0.], dtype=np.float32)]

In [24]:
model.set_weights(new_weights)

In [25]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [26]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [27]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - loss: 27.8933  
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.5713 
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 27.2353 
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 26.9211 
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.5698 
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 26.2096 
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.8481 
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.4712 
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 25.0559 
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 24.6670
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 24.2203 
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.8094 
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 23.4077 
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 22.9516
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 22.5117 
Epoch 16/75
4/4 ━━

In [28]:
model.get_weights()

[array([[0.37379706, 0.37379706],
        [0.36567968, 0.36567968]], dtype=float32),
 array([0.27246153, 0.27246153], dtype=float32),
 array([[0.37304997],
        [0.37304997]], dtype=float32),
 array([0.20483269], dtype=float32)]